# Generated by Django 3.1 on 2020-11-12 09:04

from django.db import migrations

import swiftmovers.core.db.fields
import swiftmovers.core.utils.editorjs


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0015_migrate_from_draftjs_to_editorjs_format"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="content_json",
            field=swiftmovers.core.db.fields.SanitizedJSONField(
                blank=True,
                default=dict,
                sanitizer=swiftmovers.core.utils.editorjs.clean_editor_js,
            ),
        ),
        migrations.AlterField(
            model_name="pagetranslation",
            name="content_json",
            field=swiftmovers.core.db.fields.SanitizedJSONField(
                blank=True,
                default=dict,
                sanitizer=swiftmovers.core.utils.editorjs.clean_editor_js,
            ),
        ),
    ]
