# Generated by Django 4.1.3 on 2022-12-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zone',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='zone',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
