# Generated by Django 4.1.3 on 2022-11-19 12:20

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import django_measurement.models
import measurement.measures.mass
import swiftmovers.core.db.fields
import swiftmovers.core.utils.editor
import swiftmovers.core.weight


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('countries', django_countries.fields.CountryField(blank=True, default=[], max_length=746, multiple=True)),
                ('default', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('price', 'Price based shipping'), ('weight', 'Weight based shipping')], max_length=30)),
                ('minimum_order_weight', django_measurement.models.MeasurementField(blank=True, default=swiftmovers.core.weight.zero_weight, measurement=measurement.measures.mass.Mass, null=True)),
                ('maximum_order_weight', django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.mass.Mass, null=True)),
                ('maximum_delivery_days', models.PositiveIntegerField(blank=True, null=True)),
                ('minimum_delivery_days', models.PositiveIntegerField(blank=True, null=True)),
                ('description', swiftmovers.core.db.fields.SanitizedJSONField(blank=True, null=True, sanitizer=swiftmovers.core.utils.editor.clean_editor_js)),
                ('shipping_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_methods', to='shipping.shippingzone')),
            ],
        ),
    ]
