# Generated by Django 3.2.16 on 2022-12-16 11:04

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import swiftmovers.core.utils.json_serializer


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0001_initial'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethodZoneListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_order_price_amount', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('maximum_order_price_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('price_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.AlterModelOptions(
            name='shippingmethod',
            options={'ordering': ('pk',)},
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, encoder=swiftmovers.core.utils.json_serializer.CustomJsonEncoder, null=True),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='private_metadata',
            field=models.JSONField(blank=True, default=dict, encoder=swiftmovers.core.utils.json_serializer.CustomJsonEncoder, null=True),
        ),
        migrations.AddIndex(
            model_name='shippingmethod',
            index=django.contrib.postgres.indexes.GinIndex(fields=['private_metadata'], name='shippingmethod_p_meta_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingmethod',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='shippingmethod_meta_idx'),
        ),
        migrations.AddField(
            model_name='shippingmethodzonelisting',
            name='shipping_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Zone_listings', to='shipping.shippingmethod'),
        ),
        migrations.AddField(
            model_name='shippingmethodzonelisting',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_method_listings', to='zones.zone'),
        ),
        migrations.AlterUniqueTogether(
            name='shippingmethodzonelisting',
            unique_together={('shipping_method', 'zone')},
        ),
    ]
