# Generated by Django 4.1.3 on 2022-12-03 14:56

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import swiftmovers.core.utils.json_serializer


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', models.JSONField(blank=True, default=dict, encoder=swiftmovers.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=swiftmovers.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('fulfillment_order', models.PositiveIntegerField(editable=False)),
                ('status', models.CharField(choices=[('fulfilled', 'Fulfilled'), ('refunded', 'Refunded'), ('returned', 'Returned'), ('replaced', 'Replaced'), ('refunded_and_returned', 'Refunded and returned'), ('canceled', 'Canceled'), ('waiting_for_approval', 'Waiting for approval')], default='fulfilled', max_length=32)),
                ('tracking_number', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipping_refund_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('total_refund_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
            ],
            options={
                'ordering': ('pk',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='zones.zone'),
        ),
        migrations.CreateModel(
            name='FulfillmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('fulfillment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.fulfillment')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_lines', to='orders.orderline')),
            ],
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='order',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='fulfillment',
            index=django.contrib.postgres.indexes.GinIndex(fields=['private_metadata'], name='fulfillment_p_meta_idx'),
        ),
        migrations.AddIndex(
            model_name='fulfillment',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='fulfillment_meta_idx'),
        ),
    ]
