# Generated by Django 4.1.3 on 2022-12-02 14:27

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('currency_code', models.CharField(max_length=3)),
                ('default_country', django_countries.fields.CountryField(max_length=2)),
                ('allocation_strategy', models.CharField(choices=[('prioritize-sorting-order', 'Prioritize sorting order'), ('prioritize-high-risk', 'Prioritize high risk')], default='prioritize-sorting-order', max_length=255)),
                ('is_with_traffic', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
    ]
