# Generated by Django 3.2.19 on 2023-06-08 14:07

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0001_initial'),
        ('channel', '0001_initial'),
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='categories',
            field=models.ManyToManyField(blank=True, to='product.Category'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='collections',
            field=models.ManyToManyField(blank=True, to='product.Collection'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='products',
            field=models.ManyToManyField(blank=True, to='product.Product'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='variants',
            field=models.ManyToManyField(blank=True, to='product.ProductVariant'),
        ),
        migrations.AddField(
            model_name='saletranslation',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='discount.sale'),
        ),
        migrations.AddField(
            model_name='salechannellisting',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_listings', to='channel.channel'),
        ),
        migrations.AddField(
            model_name='salechannellisting',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_listings', to='discount.sale'),
        ),
        migrations.AddField(
            model_name='sale',
            name='categories',
            field=models.ManyToManyField(blank=True, to='product.Category'),
        ),
        migrations.AddField(
            model_name='sale',
            name='collections',
            field=models.ManyToManyField(blank=True, to='product.Collection'),
        ),
        migrations.AddField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(blank=True, to='product.Product'),
        ),
        migrations.AddField(
            model_name='sale',
            name='variants',
            field=models.ManyToManyField(blank=True, to='product.ProductVariant'),
        ),
        migrations.AddField(
            model_name='orderdiscount',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='order.order'),
        ),
        migrations.AlterUniqueTogether(
            name='vouchertranslation',
            unique_together={('language_code', 'voucher')},
        ),
        migrations.AlterUniqueTogether(
            name='vouchercustomer',
            unique_together={('voucher', 'customer_email')},
        ),
        migrations.AlterUniqueTogether(
            name='voucherchannellisting',
            unique_together={('voucher', 'channel')},
        ),
        migrations.AlterUniqueTogether(
            name='saletranslation',
            unique_together={('language_code', 'sale')},
        ),
        migrations.AlterUniqueTogether(
            name='salechannellisting',
            unique_together={('sale', 'channel')},
        ),
        migrations.AddIndex(
            model_name='orderdiscount',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name', 'translated_name'], name='discount_or_name_d16858_gin'),
        ),
    ]
