# Generated by Django 3.2.16 on 2022-12-16 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('checkouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='items.product'),
        ),
    ]
