# Generated by Django 4.1.3 on 2022-11-19 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, null=True)),
                ('created', models.DateTimeField(null=True)),
                ('external_url', models.URLField(max_length=2048, null=True)),
                ('invoice_file', models.FileField(upload_to='invoices')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='orders.order')),
            ],
        ),
    ]
