# Generated by Django 4.1.3 on 2022-11-19 12:27

from django.db import migrations, models
import django.db.models.deletion
import django_measurement.models
import measurement.measures.mass
import swiftmovers.core.db.fields
import swiftmovers.core.utils.editor
import swiftmovers.core.weight


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('description', swiftmovers.core.db.fields.SanitizedJSONField(blank=True, null=True, sanitizer=swiftmovers.core.utils.editor.clean_editor_js)),
                ('description_plaintext', models.TextField(blank=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='category-backgrounds')),
                ('background_image_alt', models.CharField(blank=True, max_length=128)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='items.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('kind', models.CharField(choices=[('normal', 'A standard product type.'), ('gift_card', 'A gift card product type.')], max_length=32)),
                ('has_variants', models.BooleanField(default=True)),
                ('is_shipping_required', models.BooleanField(default=True)),
                ('is_digital', models.BooleanField(default=False)),
                ('weight', django_measurement.models.MeasurementField(default=swiftmovers.core.weight.zero_weight, measurement=measurement.measures.mass.Mass)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('description', swiftmovers.core.db.fields.SanitizedJSONField(blank=True, null=True, sanitizer=swiftmovers.core.utils.editor.clean_editor_js)),
                ('description_plaintext', models.TextField(blank=True)),
                ('search_document', models.TextField(blank=True, default='')),
                ('search_index_dirty', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('charge_taxes', models.BooleanField(default=True)),
                ('weight', django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.mass.Mass, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='items.category')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='items.producttype')),
            ],
        ),
    ]
